
// All generated by AI, just ask for help to create a UI for me that is not that important
export default function Loading(){
    return (
            <div className="relative min-h-screen overflow-hidden bg-[#090707] flex items-center justify-center">

            {/* Ambient background glow */}
            <div className="absolute inset-0 pointer-events-none">
                <div className="absolute left-1/2 top-1/2 h-[500px] w-[500px] -translate-x-1/2 -translate-y-1/2 rounded-full bg-orange-500/5 blur-[120px]" />

                <div className="absolute left-0 top-1/3 h-40 w-40 rounded-full bg-purple-500/5 blur-[100px]" />

                <div className="absolute right-0 bottom-1/3 h-40 w-40 rounded-full bg-blue-500/5 blur-[100px]" />
            </div>

            {/* Main HUD container */}
            <div className="relative z-10 flex w-[90%] max-w-[480px] flex-col items-center">

                {/* Top decorative HUD lines */}
                <div className="mb-8 flex w-full items-center gap-3">
                <div className="h-[1px] flex-1 bg-gradient-to-r from-transparent via-orange-500/60 to-orange-400" />

                <div className="h-2 w-2 rotate-45 border border-orange-400 shadow-[0_0_10px_rgba(249,115,22,0.8)]" />

                <div className="h-[1px] flex-1 bg-gradient-to-l from-transparent via-orange-500/60 to-orange-400" />
                </div>


                {/* Loading ring */}
                <div className="relative mb-10 h-32 w-32">

                {/* Outer glow */}
                <div className="absolute inset-0 rounded-full bg-orange-500/10 blur-2xl" />

                {/* Outer ring */}
                <div className="absolute inset-0 rounded-full border border-orange-500/20" />

                {/* Rotating orange ring */}
                <div
                    className="
                    absolute inset-1
                    animate-spin
                    rounded-full
                    border-[3px]
                    border-transparent
                    border-t-orange-400
                    border-r-orange-500
                    shadow-[0_0_18px_rgba(249,115,22,0.6)]
                    "
                />

                {/* Blue accent ring */}
                <div
                    className="
                    absolute inset-3
                    rounded-full
                    border-2
                    border-transparent
                    border-b-blue-400
                    animate-[spin_3s_linear_infinite_reverse]
                    opacity-80
                    shadow-[0_0_12px_rgba(96,165,250,0.5)]
                    "
                />

                {/* Inner circle */}
                <div className="absolute inset-7 flex items-center justify-center rounded-full border border-orange-400/30 bg-black/50 backdrop-blur-sm">

                    {/* Clean Quest style emblem */}
                    <div className="relative h-7 w-7 rotate-45 border border-orange-300 shadow-[0_0_15px_rgba(251,146,60,0.7)]">
                    <div className="absolute inset-1 border border-orange-400/50" />
                    </div>

                </div>

                {/* Small HUD ticks */}
                <span className="absolute left-1/2 -top-3 h-2 w-[2px] -translate-x-1/2 bg-orange-400" />
                <span className="absolute left-1/2 -bottom-3 h-2 w-[2px] -translate-x-1/2 bg-orange-400" />
                <span className="absolute -left-3 top-1/2 h-[2px] w-2 -translate-y-1/2 bg-blue-400" />
                <span className="absolute -right-3 top-1/2 h-[2px] w-2 -translate-y-1/2 bg-purple-400" />

                </div>


                {/* Loading information panel */}
                <div
                className="
                    relative w-full
                    border border-orange-400/40
                    bg-black/60
                    px-6 py-5
                    backdrop-blur-md
                    shadow-[0_0_30px_rgba(249,115,22,0.08)]
                "
                >

                {/* Angular corners */}
                <div className="absolute -left-[1px] -top-[1px] h-4 w-4 border-l-2 border-t-2 border-orange-400" />
                <div className="absolute -right-[1px] -top-[1px] h-4 w-4 border-r-2 border-t-2 border-orange-400" />
                <div className="absolute -left-[1px] -bottom-[1px] h-4 w-4 border-l-2 border-b-2 border-orange-400" />
                <div className="absolute -right-[1px] -bottom-[1px] h-4 w-4 border-r-2 border-b-2 border-orange-400" />

                {/* Header */}
                <div className="mb-4 flex items-center justify-between">

                    <div>
                    <p className="text-[10px] uppercase tracking-[0.3em] text-orange-400/70">
                        Clean Quest
                    </p>

                    <h2 className="mt-1 text-lg font-semibold tracking-widest text-orange-100">
                        LOADING
                    </h2>
                    </div>

                    <div className="text-[10px] tracking-widest text-orange-400/60">
                    SYSTEM
                    </div>

                </div>


                {/* Progress bar */}
                <div className="relative h-2 overflow-hidden border border-orange-400/30 bg-black/70">

                    <div
                    className="
                        h-full w-[65%]
                        bg-gradient-to-r
                        from-orange-600
                        via-orange-400
                        to-yellow-200
                        shadow-[0_0_12px_rgba(251,146,60,0.9)]
                        animate-pulse
                    "
                    />

                </div>


                {/* Status */}
                <div className="mt-4 flex items-center justify-between">

                    <div className="flex items-center gap-2">
                    <span className="h-2 w-2 animate-pulse rounded-full bg-orange-400 shadow-[0_0_8px_rgba(251,146,60,1)]" />

                    <span className="text-xs tracking-wider text-gray-300">
                        Loading please wait...
                    </span>
                    </div>

                    <span className="text-xs font-mono text-orange-400">
                    65%
                    </span>

                </div>

                </div>


                {/* Bottom HUD details */}
                <div className="mt-5 flex w-full items-center justify-between text-[9px] uppercase tracking-[0.25em] text-gray-600">

                <span>Preparing Quest</span>

                <div className="flex gap-1">
                    <span className="h-1 w-4 bg-orange-500/50" />
                    <span className="h-1 w-4 bg-orange-500/30" />
                    <span className="h-1 w-4 bg-orange-500/20" />
                </div>

                <span>01 // 04</span>

                </div>

            </div>
            </div>
        );
}